// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otsquyhcumtnqrgfgwdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90c3F1eWhjdW10bnFyZ2Znd2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTIxNzIsImV4cCI6MjA2NDY4ODE3Mn0.d6SjqiExuVXrzXbuVI364bR0FiFNHd8ZtGUe6WbJh1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);